### ISSUE TITLE
Plugin not start with 2 groups

### ISSUE THREAD

**Issue by mihaigsm2003** [partiusfabaa/cs2-LiteVIP#10]
if add more then 1 group plugin not start:
```cpp
"Groups": {
    "GROUP_NAME1": {
      "Health": 100,
      "Armor": 100,
      "Gravity": 1,
      "Money": 1000,
      "SmokeColor": "255 255 255",
      "Healthshot": 1,
      "JumpsCount": 2,
      "RainbowModel": true,
      "Items": [
        "weapon_molotov",
        "weapon_ak47"
      ],
      "DecoySettings": {
        "DecoyTeleport": true,
        "DecoyCountInOneRound": 1,
        "DecoyCountToBeIssued": 1
      }
    }
	    "GROUP_NAME": {
      "Health": 100,
      "Armor": 100,
      "Gravity": 1,
      "Money": 1000,
      "SmokeColor": "255 255 255",
      "Healthshot": 1,
      "JumpsCount": 2,
      "RainbowModel": true,
      "Items": [
        "weapon_molotov"
      ],
      "DecoySettings": {
        "DecoyTeleport": true,
        "DecoyCountInOneRound": 1,
        "DecoyCountToBeIssued": 1
      }
    }
  },

**Comment by partiusfabaa** [comment]
> if add more then 1 group plugin not start:
> 
> ```c++
> "Groups": {
>     "GROUP_NAME1": {
>       "Health": 100,
>       "Armor": 100,
>       "Gravity": 1,
>       "Money": 1000,
>       "SmokeColor": "255 255 255",
>       "Healthshot": 1,
>       "JumpsCount": 2,
>       "RainbowModel": true,
>       "Items": [
>         "weapon_molotov",
>         "weapon_ak47"
>       ],
>       "DecoySettings": {
>         "DecoyTeleport": true,
>         "DecoyCountInOneRound": 1,
>         "DecoyCountToBeIssued": 1
>       }
>     }, //here
> 	    "GROUP_NAME": {
>       "Health": 100,
>       "Armor": 100,
>       "Gravity": 1,
>       "Money": 1000,
>       "SmokeColor": "255 255 255",
>       "Healthshot": 1,
>       "JumpsCount": 2,
>       "RainbowModel": true,
>       "Items": [
>         "weapon_molotov"
>       ],
>       "DecoySettings": {
>         "DecoyTeleport": true,
>         "DecoyCountInOneRound": 1,
>         "DecoyCountToBeIssued": 1
>       }
>     } //If the group is the last group, no comma is needed
>   },
> ```

you missed a comma

**Comment by mihaigsm2003** [comment]
> > if add more then 1 group plugin not start:
> > ```c++
> > "Groups": {
> >     "GROUP_NAME1": {
> >       "Health": 100,
> >       "Armor": 100,
> >       "Gravity": 1,
> >       "Money": 1000,
> >       "SmokeColor": "255 255 255",
> >       "Healthshot": 1,
> >       "JumpsCount": 2,
> >       "RainbowModel": true,
> >       "Items": [
> >         "weapon_molotov",
> >         "weapon_ak47"
> >       ],
> >       "DecoySettings": {
> >         "DecoyTeleport": true,
> >         "DecoyCountInOneRound": 1,
> >         "DecoyCountToBeIssued": 1
> >       }
> >     }, //here
> > 	    "GROUP_NAME": {
> >       "Health": 100,
> >       "Armor": 100,
> >       "Gravity": 1,
> >       "Money": 1000,
> >       "SmokeColor": "255 255 255",
> >       "Healthshot": 1,
> >       "JumpsCount": 2,
> >       "RainbowModel": true,
> >       "Items": [
> >         "weapon_molotov"
> >       ],
> >       "DecoySettings": {
> >         "DecoyTeleport": true,
> >         "DecoyCountInOneRound": 1,
> >         "DecoyCountToBeIssued": 1
> >       }
> >     } //If the group is the last group, no comma is needed
> >   },
> > ```
> 
> you missed a comma

i try all combinations, for me not work, only with 1 group, also i tested combination from `readme`, not work for me:

```cpp
{
  "JumpsNoVip": 1,
  "Admins": [76561144096558223],//SteamID64 should be separated by commas
  "Delay": 2,			//At what interval to issue the VIP(second)
  "VipTestSettings": {
    "VipTestEnabled": true, 	//is VIP-TEST enabled? true - yes, false - no
    "VipTestTime": 3600,	//Duration of VIP test issuance (in seconds)
    "VipTestGroup": "VIP1",	//Assigned VIP Group
    "VipTestCount": 4		//How many times can a player take the VIP test
  },
  "Groups": {
    "VIP1": {
      "Health": 115,
      "Armor": 115,
      "Gravity": 0.9,
      "Money": 5000,
      "SmokeColor": "random",
      "Healthshot": 1,
      "JumpsCount": 1
    },
    "VIP2": {
      "Health": 175,		//amount of health
      "Armor": 175,		//amount of armor
      "Gravity": 0.7,		//Gravity: less than 1 is low, more than 1 is high.
      "Money": 16000,		//amount of money at spawning
      "SmokeColor": "255 11 22",//color R G B is spelled with a space or "random" and then you'll have a different color for every shot.
      "Healthshot": 1,		//syringe count at revival
      "JumpsCount": 2,		//number of additional jumps
      "RainbowModel": true, 	//true - on, false - off
      "Items": ["weapon_molotov", "weapon_ak47"], //items given out at revival. If you don't need anything, leave the field blank
      "DecoySettings": {	
        "DecoyTeleport": true,	  //Is the teleportation grenade enabled? true - yes, false - no
        "DecoyCountInOneRound": 1,//how many teleportation grenades can be used in one round?
	"DecoyCountToBeIssued": 1 //number of teleportation grenades issued
      }
    }
  },
  "Connection": {
    "Host": 	"HOST",
    "Database": "DATABASE",
    "User": 	"USER",
    "Password": "PASSWORD"
  }
}

**Comment by mihaigsm2003** [comment]
this is my fully config:
```cpp
{
  "JumpsNoVip": 2,
  "Admins": [76561198047676738,76561198369935453],
  "Delay": 2,
  "VipTestSettings": {
    "VipTestEnabled": true,
    "VipTestTime": 86400,
    "VipTestGroup": "VipTest",
    "VipTestCount": 1
  },
"Groups": {
      "PRO": {
      "Health": 115,
      "Armor": 180,
      "Gravity": 0.8,
      "Money": 16000,
      "SmokeColor": "random",
      "Healthshot": 1,
      "JumpsCount": 2,
      "RainbowModel": true,
      "Items": [
	"weapon_molotov",
   	 "weapon_hegrenade",
	"weapon_smokegrenade",
	"weapon_flashbang"
	 	],
      "DecoySettings": {
        "DecoyTeleport": false,
        "DecoyCountInOneRound": 1,
        "DecoyCountToBeIssued": 1
      }
    }, //here
	  "VipTest": {
      "Health": 105,
      "Armor": 150,
      "Gravity": 0.9,
      "Money": 14000,
      "SmokeColor": "255 255 255",
      "Healthshot": 1,
      "JumpsCount": 2,
      "RainbowModel": true,
      "Items": [
        "weapon_molotov"
      ],
      "DecoySettings": {
        "DecoyTeleport": false,
        "DecoyCountInOneRound": 1,
        "DecoyCountToBeIssued": 1
      }
	  }
	     },
  "Connection": {
    "Host": "172.18.0.1",
    "Database": "LiteVip",
    "User": "root",
    "Password": "edit"
  }
}

**Comment by partiusfabaa** [comment]
> Author

Did you remove comments from the readme of the configuration when you used it?

**Comment by mihaigsm2003** [comment]
> > Author
> 
> Did you remove comments from the readme of the configuration when you used it?

yeah, i not remove comments, but my config its same. also, in one group if remove decoy settings stiil plugin lot loaded.
for momment i dissable plugin becouse when i change map server crashes. Also need to remove load money and items in pistol rounds.
