### ISSUE TITLE
[BUG] Console spamming error

### ISSUE THREAD

**Issue by GreeNyTMs** [partiusfabaa/cs2-LiteVIP#12]
Hello, my console still spamming this error, I need it fix it.
Can you help me please?

![image](https://github.com/partiusfabaa/cs2-LiteVIP/assets/149469349/4c2b15d7-9bd5-436a-a3f7-d84e1450672e)

**Comment by partiusfabaa** [comment]
try [this](https://github.com/partiusfabaa/cs2-LiteVIP/releases/tag/v1.0.7.3) version
