### ISSUE TITLE
Native 57b77d8f was invoked on a non-main thread

### ISSUE THREAD

**Issue by MinnDe** [partiusfabaa/cs2-LiteVIP#20]
After logging in and logging out of the server, I get the following error. Plugin is not working.
![Screenshot_6](https://github.com/partiusfabaa/cs2-LiteVIP/assets/64688461/9883f9b8-ffb2-41f1-94cf-20fa987a3444)
![Screenshot_5](https://github.com/partiusfabaa/cs2-LiteVIP/assets/64688461/c6395ad6-8b9a-4e12-b451-283e00d36811)

**Comment by partiusfabaa** [comment]
VIP With Cssharp v99+ will not work. Put v98
