### ISSUE TITLE
Money code

### ISSUE THREAD

**Issue by skaen** [partiusfabaa/cs2-LiteVIP#21]
I edit the output as follows:

```
if (group.Money != null && !g_bPistolRound)
    if (group.Money.Value != -1)
        if (moneyServices != null)
        {
            var stringCvar = ConVar.Find("mp_maxmoney");
            var Balance = moneyServices.Account;
            var UpdateBalance = moneyServices.Account + group.Money.Value;

            if (UpdateBalance > stringCvar!.GetPrimitiveValue<int>())
            {
                Balance = stringCvar!.GetPrimitiveValue<int>();
            }
            else
            {
                Balance = UpdateBalance;
            }

            moneyServices.Account = Balance > 16000 ? 16000 : Balance;
        }
```

**Comment by partiusfabaa** [comment]
> I edit the output as follows:
> 
> ```
> if (group.Money != null && !g_bPistolRound)
>     if (group.Money.Value != -1)
>         if (moneyServices != null)
>         {
>             var stringCvar = ConVar.Find("mp_maxmoney");
>             var Balance = moneyServices.Account;
>             var UpdateBalance = moneyServices.Account + group.Money.Value;
> 
>             if (UpdateBalance > stringCvar!.GetPrimitiveValue<int>())
>             {
>                 Balance = stringCvar!.GetPrimitiveValue<int>();
>             }
>             else
>             {
>                 Balance = UpdateBalance;
>             }
> 
>             moneyServices.Account = Balance > 16000 ? 16000 : Balance;
>         }
> ```

Not sure what your point is, but for me if `mp_maxmoney` was 16000, I just couldn't get more.
